cartridge/urls.py
from .views import *
from django.urls import path

urlpatterns = [
    path('', CartListView.as_view(), name='stock'),
    path('stock/', CartListView.as_view(), name='stock'),

    path('<int:pk>', CartDetailView.as_view(), name='details_view'),
    path('<int:pk>/update', EditUpdateView.as_view(), name='edit_update_view'),
    path('transfe_for_use', transfer, name='transfer_for_use'),
    path('<int:pk>/delete', CartDeleteView.as_view(), name='delete_view'),

    path('add_items/', add_items, name='add_items'),
    path('use/', UseListView.as_view(), name='use'),

    path('empty/', EmptyListView.as_view(), name='empty'),
    path('worked_firms/', WorkedfirmsListView.as_view(), name='worked_firms'),
    path('basket/', BasketListView.as_view(), name='basket'),
    path('massive_change_room/', massive_change_room, name='massive_change_room'),

    path('add_name/', add_name, name='add_name'),
    path('tree_list/', tree_list, name='tree_list'),
    path('add_manufacture/', add_manufacture, name='add_manufacture'),
    path('print_pl/', print_pl, name='print_pl'),
    path('print_cart/', print_cart, name='print_cart'),
    path('to_firm/', to_firm, name='to_firm'),
    path('from_firm/', from_firm, name='from_firm'),
    # path('<int:pk>/history', some_view, name='history_cart')


]

djangoCarts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('cartridge/', include('cartridge.urls')),
                  path('', include('cartridge.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cartridge/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.contenttypes.models import ContentType
from simple_history.models import HistoricalRecords
import datetime


class Manufacturer(models.Model):  # Производитель
    manufacturer = models.CharField("Производитель", max_length=50, unique=True, db_index=True)
    comments = models.CharField("Комментарии", max_length=100, blank=True)

    class Meta:
        verbose_name = 'Производитель'
        verbose_name_plural = 'Производители'

    def __str__(self):
        return str(self.manufacturer)


class Placements(models.Model):  # Помещения
    barcode = models.IntegerField('Штрихкод', unique=True, db_index=True)
    name = models.CharField("Помещение", max_length=50, unique=True, db_index=True)
    branch = models.CharField("Корпус", max_length=50, blank=True, null=True)

    class Meta:
        verbose_name = 'Помещение'
        verbose_name_plural = 'Помещения'

    def __str__(self):
        return str(self.name)


class NameСartridge(models.Model):  # Названия картриджей
    name = models.CharField("Название картриджа", max_length=50, unique=True, db_index=True)
    comments = models.CharField("Комментарии", max_length=100, blank=True)

    class Meta:
        verbose_name = 'Название картриджа'
        verbose_name_plural = 'Названия картриджей'

    def __str__(self):
        return str(self.name)


class Cartridges(models.Model):  # Картриджи
    barcode = models.CharField('Штрихкод', unique=True, db_index=True, max_length=50)
    cartName = models.ForeignKey('NameСartridge', default=None, on_delete=models.PROTECT)
    placeName = models.ForeignKey('Placements', on_delete=models.PROTECT)
    manufacturerName = models.ForeignKey('Manufacturer', default=None, on_delete=models.PROTECT)
    date = models.DateTimeField("Дата изменения", default=datetime.datetime.now().strftime("%d.%m.%Y %H:%M"))
    col = models.IntegerField('Перезаправки', db_index=True, blank=True, null=True)
    history = HistoricalRecords()

    def __str__(self):
        return str(self.barcode) + " | " + str(self.cartName)

    class Meta:
        verbose_name = 'Картридж'
        verbose_name_plural = 'Картриджи'


class Status(models.Model):  # Помещения
    status = models.CharField("Статус", max_length=50, unique=True, db_index=True)

    class Meta:
        verbose_name = 'Статус'
        verbose_name_plural = 'Статус'

    def __str__(self):
        return str(self.status)


class ChangeLog(models.Model):
    barcode_h = models.CharField('Штрихкод', blank=True, null=True, max_length=50)
    cartName_h = models.CharField('Модель', max_length=250, blank=True, null=True)
    placeName_h = models.CharField('Помещение', max_length=50, blank=True, null=True)
    manufacturerName_h = models.CharField('Производитель', max_length=50, blank=True, null=True)
    date_h = models.DateTimeField("Дата изменения", null=True)
    comments_h = models.CharField('Комментарии', max_length=250, blank=True, null=True)

    class Meta:
        verbose_name = _('Журнал изменений')
        verbose_name_plural = _('Журналы изменений')

    def __str__(self):
        return str(self.barcode_h) + " " + str(self.manufacturerName_h) + " " + str(self.cartName_h) + " " + str(self.date_h)

cartridge/views.py
from django.core.serializers.json import DjangoJSONEncoder
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.decorators.csrf import ensure_csrf_cookie, csrf_protect
from .models import Cartridges, Placements, NameСartridge, Manufacturer, ChangeLog
from .forms import ManufacturerForm, NameСartridgeForm, PlacementsForm, CartridgesForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView
from io import BytesIO
import datetime
import barcode
import random
import json

list_checks = []
numbers = []


class CartListView(ListView):
    model = Cartridges
    template_name = 'cartridge/stock.html'

    def get_context_data(self, **kwargs):
        context = super(CartListView, self).get_context_data(**kwargs)
        context['cartridge_list_view'] = Cartridges.objects.filter(placeName=2)
        context['qs_json'] = json.dumps(list(Cartridges.objects.values()), cls=DjangoJSONEncoder)
        return context


class UseListView(ListView):
    model = Cartridges
    template_name = 'cartridge/use.html'

    def post(self, request, *args, **kwargs):
        checks = request.POST.getlist('check')
        if "ended_cart" in self.request.POST:
            for num in checks:
                Cartridges.objects.filter(barcode=num).update(placeName='0')
            return redirect('use')
        elif "return_cart" in self.request.POST:
            for num in checks:
                Cartridges.objects.filter(barcode=num).update(placeName='2')
            return redirect('use')

    def get_context_data(self, **kwargs):
        context = super(UseListView, self).get_context_data(**kwargs)
        context['cartridge_list_view'] = Cartridges.objects.exclude(placeName=0).exclude(placeName=1).exclude(placeName=2).exclude(placeName=3)
        context['qs_json'] = json.dumps(list(Cartridges.objects.values()), cls=DjangoJSONEncoder)
        return context


class EmptyListView(ListView):
    model = Cartridges
    template_name = 'cartridge/empty.html'

    def get_context_data(self, **kwargs):
        context = super(EmptyListView, self).get_context_data(**kwargs)
        context['empty_carts'] = Cartridges.objects.filter(placeName=0)
        return context


class WorkedfirmsListView(ListView):
    model = Cartridges
    template_name = 'cartridge/worked_firms.html'

    def get_context_data(self, **kwargs):
        context = super(WorkedfirmsListView, self).get_context_data(**kwargs)
        context['worked_carts'] = Cartridges.objects.filter(placeName=1)
        return context


class BasketListView(ListView):
    model = Cartridges
    template_name = 'cartridge/basket.html'

    def get_context_data(self, **kwargs):
        context = super(BasketListView, self).get_context_data(**kwargs)
        context['basket'] = Cartridges.objects.filter(placeName=3)
        return context


class CartDetailView(DetailView):
    model = Cartridges
    template_name = 'cartridge/details_view.html'
    context_object_name = 'cartridge_details_view'
    success_url = reverse_lazy('add_items')

    def get_context_data(self, **kwargs):
        context = super(CartDetailView, self).get_context_data(**kwargs)
        history = ChangeLog.objects.filter(barcode_h=kwargs['object'].barcode)
        context['history'] = history
        return context


class EditUpdateView(UpdateView):
    model = Cartridges
    form_class = CartridgesForm
    template_name = 'cartridge/edit_cartridge_info.html'
    success_url = reverse_lazy('stock')


class CartDeleteView(DeleteView):
    model = Cartridges
    template_name = 'cartridge/stock.html'
    success_url = reverse_lazy('stock')


def massive_change_room(request):
    carts = ''
    message = ''
    display_error_msg = 'none'
    display_success_msg = 'none'
    display = 'none'
    autofocus = 'autofocus'
    display_form = 'none'

    if request.GET:
        search_post = request.GET.get('search')
        if len(search_post) > 13:
            display_error_msg = 'block'
            message = 'Максимальная длина номера 13 символов'
            autofocus = 'autofocus'
        elif len(search_post) == 0:
            display_error_msg = 'none'
            autofocus = 'autofocus'
        else:
            carts = Cartridges.objects.filter(barcode=search_post)
            if carts:
                display_form = 'block'
                numbers.append(search_post)
                autofocus = ''
            else:
                display_error_msg = 'block'
                message = 'Такого номера нет в базе'
                autofocus = 'autofocus'

    cart = CartridgesForm()
    place = PlacementsForm()

    if request.POST:

        place = PlacementsForm(request.POST)
        barcode_place = place.data['barcode']

        if len(barcode_place) > 13:
            display_error_msg = 'block'
            message = 'Максимальная длина номера 13 символов'
        elif len(barcode_place) == 0:
            display_error_msg = 'none'
        else:
            places = Placements.objects.filter(barcode=barcode_place)
            if places:  # если номер есть в базе
                place_id = [i.pk for i in places][0]  # получаем id помещения
                if numbers:  # если картридж отсканирован
                    Cartridges.objects.filter(barcode=numbers[0]).update(placeName=place_id, date=datetime.datetime.now().strftime("%Y-%m-%d %H:%M"))

                    p = Placements.objects.get(id=place_id)
                    ChangeLog.objects.create(barcode_h=numbers[0], placeName_h=p, date_h=datetime.datetime.now().strftime("%Y-%m-%d %H:%M"), comments_h=f'Картридж {numbers[0]} передан на {p}')  # запись в журнал изменений

                    display_success_msg = 'block'
                    message = 'Картридж передан'
                    carts = Cartridges.objects.filter(barcode=numbers[0])
                    numbers.clear()
                    place = PlacementsForm(None)
                    autofocus = 'autofocus'
                    display_form = 'none'
                else:
                    display_error_msg = 'block'
                    message = 'Не выбран картридж'
                    place = PlacementsForm(None)
                    autofocus = 'autofocus'
                    display_form = 'none'
            else:
                if numbers:
                    carts = Cartridges.objects.filter(barcode=numbers[0])
                    display_error_msg = 'block'
                    message = 'Такого помещения нет в базе'
                    place = PlacementsForm(None)
                    autofocus = ''
                    display_form = 'block'

    data = {
        'message': message,
        'carts': carts,
        'display': display,
        'display_error_msg': display_error_msg,
        'display_success_msg': display_success_msg,
        'cart': cart,
        'place': place,
        'page': massive_change_room,
        'autofocus': autofocus,
        'display_form': display_form
    }
    return render(request, 'cartridge/massive_change_room.html', data)


def transfer(request):
    checks = request.POST.getlist('check')
    carts_all = Cartridges.objects.all()
    list_checks.append(checks)
    message = ''
    display_error_msg = 'none'
    display_success_msg = 'none'
    display = 'none'
    nam = ''
    manuf = ''
    form = ''
    if request.POST:
        form = CartridgesForm(request.POST)['placeName']
        id_name = form.data
        if id_name:
            p = Placements.objects.get(id=id_name)
            for i in list_checks[0]:
                Cartridges.objects.filter(barcode=i).update(placeName=id_name, date=datetime.datetime.now().strftime("%Y-%m-%d %H:%M"))

                ChangeLog.objects.create(barcode_h=i, placeName_h=p, date_h=datetime.datetime.now().strftime("%Y-%m-%d %H:%M"), comments_h=f'Картридж {i} передан на {p}')

            list_checks.clear()
            return redirect('stock')

    data = {
        'carts': carts_all,
        'checks': checks,
        'form': form,
        'nam': nam,
        'manuf': manuf,
        'message': message,
        'display': display,
        'display_error_msg': display_error_msg,
        'display_success_msg': display_success_msg,
    }
    return render(request, 'cartridge/transfer_for_use.html', data)


def basket(request):
    return render(request, 'cartridge/basket.html')


@csrf_protect
@ensure_csrf_cookie
def add_name(request):
    error = ''
    display = 'none'
    name = ''
    if request.POST:
        form = NameСartridgeForm(request.POST)
        if form.is_valid():
            form.save()

            n = form.data['name']
            ChangeLog.objects.create(cartName_h=n, date_h=datetime.datetime.now().strftime("%Y-%m-%d %H:%M"), comments_h=f'Добавлена модель {n}')  # запись в журнал изменений

            name = form['name'].data
            display = 'block'
        else:
            error = 'block'
    form = NameСartridgeForm()
    data = {
        'form': form,
        'error': error,
        'display': display,
        'name': name,
    }
    return render(request, 'cartridge/add_name.html', data)


@csrf_protect
@ensure_csrf_cookie
def tree_list(request):
    place = Placements.objects.order_by('name').exclude(id=1)
    count = Placements.objects.count()
    error = ''
    display = 'none'
    name = ''
    msg_display = 'none'
    err_display = 'none'
    if request.POST:
        form = PlacementsForm(request.POST)
        bar = form.data["barcode"]
        if bar == '':
            random_num = random.randint(1111111111111, 9999999999999)
            updated_data = request.POST.copy()
            updated_data.update({'barcode': random_num})
            form = PlacementsForm(data=updated_data)
        else:
            updated_data = request.POST.copy()
            updated_data.update({'barcode': bar})
            form = PlacementsForm(data=updated_data)

cartridge/templates/cartridge/add_manufacture.html
{% extends 'cartridge/base.html' %}

{% block title %}Добавление нового производителя{% endblock %}

{% block submenu %}Справочники / Производители / Добавление нового производителя{% endblock %}

{% block content %}

    <div class="row">
        <div class="large-4 columns"  style="display: {{ display }}">
            <ul class="messages">
                <li class="success">Производитель "{{ name }}" успешно добавлен.</li>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="large-4 columns">
            <form action="" method="POST">
                {% csrf_token %}
                <div class="marginTop"></div>
                <label class="required" for="id_name">Название:</label>
                {{ form.manufacturer }}

                <div class="marginTop"></div>
                <label for="id_comment">Комментарий:</label>
                {{ form.comments }}

                <div class="marginTop input_row">
                    <a href="{% url 'add_items' %}" class="button">Вернуться</a>
                    <button class="button success" type="submit">Добавить</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

cartridge/templates/cartridge/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/mobile.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/ui-grid.min.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/detect.js' %}"></script>
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'js/jquery.cookie.js' %}"></script>

    <!-- XDSoft DateTimePicker -->
    <link rel="stylesheet" href="{% static 'js/datetime/jquery.datetimepicker.css' %}">
    <script src="{% static 'js/datetime/jquery.js' %}"></script>
    <script src="{% static 'js/datetime/jquery.datetimepicker.full.min.js' %}"></script>
    <!-- select2 -->
    <script src="{% static 'js/common.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/select2.min.css' %}">
    <!-- select2 -->
    <script src="{% static 'js/main_menu.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/pm_widget.css' %}">
    <script src="{% static 'js/pm_widget.js' %}"></script>
    <script src="{% static 'js/jquery.timepicker.min.js' %}"></script>
    <script src="{% static 'js/add_objs.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/cart/change-room-barcode.css' %}">
    <meta class="foundation-mq-small">
    <meta class="foundation-mq-medium">
    <meta class="foundation-mq-large">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
<div class="wrapper">
    <header class="header">
        <div class="logo"><a href="/">
            <img alt="nlogo" src="{% static 'img/nlogo.png' %}"/></a></div>
        <div class="submenu">
            <strong class="user_ou" title="Org">РКИБ
            </strong>admin <a class="logout_user" href="#">Выход</a>
        </div>
    </header>
    <!-- .header-->
    <div class="middle ">
        <div class="container">
            <main class="content">
                <div class="row marginTop">
                    <div class="large-10 columns">
                        <div class="breads">
                            <a href="/">
                                <img alt="home_ico" src="{% static 'img/home.png' %}"/>
                            </a> /
                            <span>
                                {% block submenu %}{% endblock %}
                            </span> /
                        </div>
                    </div>
                    <div class="large-2 columns marginTop text-right">
                    </div>
                </div>
                <div class="marginTop"></div>

                {% block content %}

                {% endblock %}
            </main>
            <!-- .content -->
        </div>
        <!-- .container-->
        <aside class="left-sidebar">
            <div class="marginTop">
                <div class="search_wrapper">
                    <form action="" method="GET">
                        <input class="search_query" type="text" name="query" onfocus="if(this.value === 'Поиск по номеру') { this.value = ''; }"
                               onfocusout="if(this.value == '') { this.value = 'Поиск по номеру'; }" value="Поиск по номеру">
                        <!---->
                        <input type="submit" class="search_button" value="">
                    </form>
                </div>
                <ul class="menu">
                    <li class="has-sub printer_ico"><span>Принтеры</span>
                        <ul>
                            <li><a href="#">Резерв</a></li>
                            <li><a href="#">Установленные</a></li>
                            <li><a href="#">Сломанные</a></li>
                            <li><a href="#">Ремонтируются</a></li>
                            <li><a href="#">Списание</a></li>
                            <li><a href="#">Буфер</a></li>
                        </ul>
                    </li>
                    <li class="has-sub cartridge_ico active"><span>Картриджи</span>
                        <ul style="display: block;">
                            <li><a href="{% url 'stock' %}">Заправленные</a></li>
                            <li><a href="{% url 'use' %}">Установленные</a></li>
                            <li><a href="{% url 'empty' %}">Пустые или сломанные</a></li>
                            <li><a href="{% url 'worked_firms' %}">Заправляются</a></li>
                            <li><a href="{% url 'basket' %}">Списание</a></li>
                            {#                            <li><a href="{%  url 'bufer' %}">Буфер</a></li>#}
                            <li><a href="{% url 'massive_change_room' %}">Смена помещения сканером ШК</a></li>
                        </ul>
                    </li>
                    <li class="has-sub dict_ico"><span>Справочники</span>
                        <ul>
                            <li><a href="#">Пользователи</a></li>
                            <li><a href="#">Организации</a></li>
                            <li><a href="{% url 'tree_list' %}">Помещения</a></li>
                            <li><a href="#">Контрагенты</a></li>
                            <li><a href="#">Акты передачи</a></li>
                            <li><a href="#">Акты возврата</a></li>
                            <li class="has-sub"><span>Принтеры</span>
                                <ul class="submenu">
                                    <li><a href="#">Названия принтеров</a></li>
                                    <li><a href="#">Типы принтеров</a></li>
                                </ul>
                            </li>
                            <li><a href="{% url 'add_items' %}">Картриджи</a></li>
                            <li><a href="{% url 'add_manufacture' %}">Производители</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </aside>
        <!-- .left-sidebar -->
    </div>
    <!-- .middle-->
</div>
<footer class="footer">
    <div class="text_in_footer">Версия: 1.0.0&nbsp;&nbsp;&nbsp;&copy;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2023
    </div>
</footer>

</body>
</html>

cartridge/templates/cartridge/details_view.html
{% extends 'cartridge/base.html' %}

{% block title %}{{ cartridge_details_view.manufacturerName }} {{ cartridge_details_view.cartName }}{% endblock %}

{% block submenu %}Картриджи / Заправленные / Добавление новых{% endblock %}

{% block content %}
    <div ng-controller="MainCtrl" class="ng-scope">
        <div class="row">
            <div class="large-8 columns">
                <form action="" method="post" class="ng-dirty ng-valid-parse ng-valid ng-valid-required">
                    {% csrf_token %}
                    <div class="marginTop"></div>
                    <label>Штрихкод: </label>
                    {{ cartridge_details_view.barcode }}

                    <div class="marginTop"></div>
                    <label for="id_cartName">Название картриджа: </label>
                    {{ cartridge_details_view.cartName }}

                    <div class="marginTop"></div>
                    <label>Производитель: </label>
                    {{ cartridge_details_view.manufacturerName }}

                    <div class="marginTop"></div>
                    <label>Помещение: </label>
                    {{ cartridge_details_view.placeName }}

                    <div class="marginTop"></div>
                    <label for="id_date">Дата добавления: </label>
                    {{ cartridge_details_view.date }}


                    <div class="marginTop"></div>
                    <label for="id_date">ИСТОРИЯ </label>
                    <div class="large-12 columns">
                        {% for h in history %}
                            {{ h.date_h }} - {{ h.comments_h }}<br>
                        {% endfor %}
                    <div class="marginTop"></div>
                    </div>

                    <div class="marginTop">
                        <a href="{% url 'stock' %}" class="button">Вернуться</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

cartridge/templates/cartridge/edit_cartridge_info.html
{% extends 'cartridge/base.html' %}

{% block title %}Редпктирование картриджа {{ manual_update.cartName }}{% endblock %}

{% block submenu %}Картриджи / Заправленные / Редактирование{% endblock %}

{% block content %}
    <div class="row">
        <div class="large-4 columns" style="display: {{ display }}">
            <ul class="success_msg" style="display: {{ msg_display }}">
                <li class="success">Штрихкод "{{ barcode_text }}" успешно присвоен картриджу {{ cart_name }}.</li>
            </ul>
            <ul class="error_msg" style="display: {{ err_display }}">
                <li class="success">{{ error }}</li>
            </ul>
        </div>
    </div>
    <div class="marginTop"></div>
    <div ng-controller="MainCtrl" class="ng-scope">
        <div class="row">
            <div class="large-5 columns">
                <form action="" method="post" class="ng-dirty ng-valid-parse ng-valid ng-valid-required">
                    {% csrf_token %}
                    <div class="marginTop">
                        <label class="required">Штрихкод</label>
                        {{ form.barcode }}

                        <div class="form_error_text cart_number_error">Обязательное поле</div>
                        <div class="marginTop">&nbsp;</div>
                    </div>
                    <div class="row">
                        <div class="large-12 columns">
                            <label class="required" for="id_cartName">Название картриджа</label>
                            <div class="input_row">
                                {{ form.cartName }}

                                <a class="dj_button" href="{% url 'add_name' %}" title="Добавить название картриджа"></a>
                            </div>
                            <div class="form_error_text cart_name_error">Обязательное поле</div>
                        </div>
                    </div>
                    <div class="marginTop"></div>
                    <div class="row">
                        <div class="large-12 columns">
                            <label class="required">Производитель</label>
                            <div class="input_row">
                                {{ form.manufacturerName }}
                                <a class="dj_button" href="{% url 'add_manufacture' %}" title="Добавить нового производителя"></a>
                            </div>
                            <div class="form_error_text cart_sklad_error">Поле должно быть выбрано</div>
                        </div>
                    </div>
                    <div class="marginTop"></div>
                    <div class="row">
                        <div class="large-12 columns">
                            <label class="required">Помещение</label>
                            <div class="input_row">

                                {{ form.placeName }}
                                <a class="dj_button" href="{% url 'tree_list' %}" title="Добавить название помещения"></a>
                            </div>
                            <div class="form_error_text cart_sklad_error">Поле должно быть выбрано</div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="marginTop wrapper-manual-datetime" style="display: block;">
                            <div class="large-6 columns">
                                <label for="id_date" class="required">Дата добавления</label>
                                <div class="calendar">
                                    {{ form.date }}
                                    <script>
                                        jQuery.datetimepicker.setLocale('ru');
                                        jQuery('#datetimepicker4').datetimepicker({
                                            format: 'd.m.Y H:i',
                                            step: 5,
                                            validateOnBlur: false,
                                            defaultDate: new Date()
                                        });
                                    </script>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="marginTop"></div>
                    <div class="marginTop">
                        <a href="{% url 'stock' %}" class="button">Вернуться</a>
                        <button class="button success" type="submit">Сохранить</button>
                        <img class="spinner" src="static/img/loader.gif">
                        <a href="#" data="full" class="generate_pdf button">Сформировать PDF</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

cartridge/templates/cartridge/print_cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>HTMLtoPDF</title>
</head>
<body>
<table>
    <tbody>
    {% if barcode_img %}
        {% for el in barcode_img %}
            {% if forloop.counter == 1 %}
                <tr>
            {% endif %}

                <td>{{ el | safe }}</td>

                {% if forloop.counter %}
                    <td style="width: 8px;"></td>
                {% endif %}

            {% if forloop.counter|divisibleby:4 %}
                </tr>
            {% endif %}

            {% if forloop.counter|divisibleby:8 %}
                <tr style="height: 11px;"></tr>
            {% endif %}

        {% endfor %}

    {% endif %}
    </tbody>
</table>
</body>
</html>

cartridge/templates/cartridge/print_pl.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>HTMLtoPDF</title>
</head>
<body>
<table>
    <tbody>
    {% if barcode_img %}
        {% for el in barcode_img %}
            {% if forloop.counter == 1 %}
                <tr>
            {% endif %}

            <td style="border: 1px solid">{{ el | safe }}</td>

            {% if forloop.counter|divisibleby:4 %}
            </tr>
            {% endif %}
        {% endfor %}
    {% endif %}
    </tbody>
</table>
</body>
</html>